### ISSUE TITLE
I want to use port 443.

### ISSUE THREAD

**Issue by ttb-inc** [shamblett/ethereum#10]
Hi

I want to use port 443 at url.
but, code if (!puri.hasPort) in Ethereum::_validateUri() dose not work.

I had setting port 443, but .hasPort is always false.
How can I use 443 port?

Thank you.

**Comment by shamblett** [comment]
Setting the port to 443 should be OK but you can't use https if that is what you are trying to do, the scheme has to be http, this test works OK -
```
 test('connectParameters - OK with port', () {
      client.connectParameters(Ethereum.rpcHttpScheme, 'localhost', 443);
      expect(client.host, 'localhost');
      expect(client.port, 443);
    });
```
Please post your code.

**Comment by ttb-inc** [comment]
Thank you for your comment.

I have to use https.
Can I use an external url?
For example, https://mainnet.infura.io/v3/...

Now I am testing by overriding EthereumINetworkAdapter. ^^

Thank you.

**Comment by ttb-inc** [comment]
`
/// The server HTTP adapter
class MyEthereumServerHTTPAdapter implements EthereumINetworkAdapter {
  /// Mime type
  static const String jsonMimeType = 'application/json';

  final Uri? _uri;
  MyEthereumServerHTTPAdapter(this._uri);

  /// Processes the HTTP request returning the  HTTP response as
  /// a map
  @override
  Future<Map<dynamic, dynamic>> httpRequest(
      Uri? uri, Map<String, dynamic> request) {
    final client = HttpClient();
    final completer = Completer<Map<dynamic, dynamic>>();

    if (this._uri != null) {
      uri = this._uri;
    }

    client.postUrl(uri!).then((HttpClientRequest req) {
      final dynamic payload = json.encode(request);
      req.headers.add(HttpHeaders.contentTypeHeader, jsonMimeType);
      req.contentLength = payload.length;
      req.write(payload);
      req.close().then((HttpClientResponse resp) {
        resp.listen(
              (dynamic data) {
            final Map<dynamic, dynamic>? payload =
            json.decode(String.fromCharCodes(data));
            completer.complete(payload);
          },
          onError: print,
        );
      });
    }, onError: print);
    return completer.future;
  }
}
`

**Comment by shamblett** [comment]
To use https you normally have to use TLS and [secure sockets](https://api.dart.dev/stable/2.12.4/dart-io/SecureSocket-class.html). 
Ethereum doesn't have a secure sockets adapter this is why https is disallowed, you can't use any url with https in it.

**Comment by weixuefeng** [comment]
So, can i use this lib for request balance from infura ?

**Comment by shamblett** [comment]
I don't know what infura is but as stated above this package does not support secure sockets so TLS working on port 443 will not work.

**Comment by weixuefeng** [comment]
> I don't know what infura is but as stated above this package does not support secure sockets so TLS working on port 443 will not work.

cool!
[infura](https://infura.io/dashboard) provide public proxy. you can getBalance, sendRawTransaction.. without build your geth node.
i want to build a wallet app with ethereum lib. and i have not myself eth rpc node.

**Comment by weixuefeng** [comment]
i'll add TLS support based on this repo. thanks very much!
