### ISSUE TITLE
[Feature Request] Ethereum Wallet functionality

### ISSUE THREAD

**Issue by AbsenceDevelopment** [shamblett/ethereum#6]
Mnemonics, private key -> public key -> address, etc

**Comment by shamblett** [comment]
Not sure what you mean, you can create a wallet with the personal api, please be more specific on what it is you want.

**Comment by AbsenceDevelopment** [comment]
Sorry for not being clear! A way to generate mnemonics and also derive public keys and addresses from it. HD Wallet functionality

**Comment by shamblett** [comment]
The client is really only an RPC2 client, if there was a way to do this stuff using RPC calls I'd add it but there doesn't seem to be, mnemonics etc seem to be generated by other means, as such I've no inclination to add this to the client, especially as I'm still building out the full RPC2 API. It may be something for the future or even for another separate library.

**Comment by AbsenceDevelopment** [comment]
I see. Thanks for the quick response!
