### ISSUE TITLE
Can you help a beginner ?

### ISSUE THREAD

**Issue by itsencrypted** [shamblett/ethereum#7]
hey there!
I'm eager to implement this and start using this package. I only know Flutter, no idea of React or JavaScript development. Can you give me some guidance about how to implement this and the main functions available to use it?
Use geth goerli and metamask.
Appreciate any help! Telegram: @itsencrypted or juliana@itsencrypted.com

Tk you!

**Comment by shamblett** [comment]
I'm not a flutter user so I can't help you with anything in this area however the package is just an RPC interface to geth, you would use it to put/get information into/out of a geth instance. It depends on what you are doing with Ethereum, you may need many or few of the RPC calls. The example should show you how to get up and running with the package, after that you just need to read the API to find the RPC method(s) you need.

If you come across any methods that exist in the Ethereum documentation that you need and are not in the package please update this issue, I will try and supply them.
