### ISSUE TITLE
getBlockByNumber returns null on Quorum

### ISSUE THREAD

**Issue by mhishami** [shamblett/ethereum#8]
Hi,

I have this to try out on Quorum.

```dart
  Future<EthereumBlock> getBlockByNumber(int blockNumber) async {
    final block = EthereumDefaultBlock()..number = blockNumber;
    return await ethClient.eth.getBlockByNumber(block, full: false);
  }
```

All I have on the response was:
```bash
Ethereum Block :
  Number : null
  Hash : null
  Parent Hash : null
  Miner : null
  Difficulty : null
  Gas Used : null
  Time : null
}
```

Should be the same for `ethereum`, or `quorum` as nothing much has changed I guess.
Can you point in the right direction on how to get the block info?

Thanks.

**Comment by shamblett** [comment]
I don't know what quorum is TBH. Are you sure you are not getting an error, try it with printError set to true and see if you get anything. 

The client was only tested against geth so maybe quorum is different, could you point me to where the quorum RPC2 api documents the getBlockByNumber method.
